# Generated by Django 5.2 on 2025-11-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_content',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
