# Generated by Django 5.2 on 2025-11-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_post_view_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_content',
            new_name='view_count',
        ),
    ]
